# fly.toml app configuration file generated for ask-the-documents-client on 2023-10-13T11:10:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ask-the-documents-client"
primary_region = "mad"

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
